### ISSUE TITLE
gui error

### ISSUE THREAD

**Issue by admzzz** [mandeep/Mausoleum#4]
```
Requirement already satisfied: PyQt5_sip<13,>=4.19.14 in /usr/local/lib/python3.5/dist-packages (from PyQt5) (4.19.18)
Installing collected packages: PyQt5
Successfully installed PyQt5-5.13.0
```

```
$ mausoleum-gui
Traceback (most recent call last):
  File "/usr/local/bin/mausoleum-gui", line 11, in <module>
    load_entry_point('mausoleum==0.8.7', 'console_scripts', 'mausoleum-gui')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/mausoleum/application.py", line 7, in <module>
ImportError: No module named PyQt5.QtCore
```

after making $ sudo python**3** setup.py install
```
$ mausoleum-gui
Cannot mix incompatible Qt library (version 0x50c03) with this library (version 0x50d00)
Aborted
```
 moreover:
```
$ sudo pip uninstall mausoleum
Can't uninstall 'mausoleum'. No files were found to uninstall.
$ sudo pip list|grep mausoleum
mausoleum                     0.8.7
```

**Comment by mandeep** [comment]
I'm not sure what could cause this but I imagine it has something to do with using different versions of libraries at the system level and user level. Do not use `sudo` with `pip` to install anything. 

Try installing pyqt5 and mausoleum in a virtual environment and let me know if the problem still exists.
