### ISSUE TITLE
GUI error + easy fix

### ISSUE THREAD

**Issue by nerun** [mandeep/Mausoleum#8]
Using `Python 3.10.6`
Installed with pip, got this error:
```
$ mausoleum-gui 
Traceback (most recent call last):
  File "/home/daniel/.local/bin/mausoleum-gui", line 8, in <module>
    sys.exit(main())
  File "/home/daniel/.local/lib/python3.10/site-packages/mausoleum/application.py", line 720, in main
    window.move(width, height)
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'

```

**Comment by nerun** [comment]
# EASY FIX
`mausoleum/application.py`, line 720:
```python
    window.move(width, height)
```
Change to:
```python
    window.move(int(width), int(height))
```

**Comment by mandeep** [comment]
Thanks for filing this. You're welcome to submit a PR if you're comfortable doing so.
